### ISSUE TITLE
Add search query in URL

### ISSUE THREAD

**Issue by Fleker** [joellord/meetupfinder#3]
If I wanted to share this list with my local friends, it'd be helpful to have a URL that will automatically search the location I specified.

**Comment by joellord** [comment]
Great idea.  I will try to put this is a future version... unless you want to work on it ;)

**Comment by Fleker** [comment]
It'd depend on the project's license, but I wouldn't mind making a PR.

**Comment by joellord** [comment]
Under MIT.  I just added the license
